//  AC types:

export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES';

export const INCREMENT = 'INCREMENT';

export const SELECT_BY_TITLE = 'SELECT_BY_TITLE';
export const SELECT_BY_DATE_RANGE = 'SELECT_BY_DATE_RANGE';

export const ADD_COMMENT = 'ADD_COMMENT';
